# Generated by Django 3.2.6 on 2021-09-13 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_tile_blogpost_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='categry',
            new_name='category',
        ),
    ]
